name: deploy
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      env:
        word: ${{secret.secret}}
      run: echo "${{word}} deploying"
