name: Nodejs
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu_latest

    steps:
    -  name: Checkout repository
       uses: actions/checkout@v2

    -  name: set up node js
    -  uses: actions/setup-node@v2
       with:
         node-version: '14'

    -  name: istall dependencies
       run: npm install

    -  name: run test
       run: npm test
